### ISSUE TITLE
Move icon to url bar

### ISSUE THREAD

**Issue by LyzardKing** [joshka/follow-mastodon-user-webextension#1]
This is a suggestion.
If the extension (which is very useful) was changed from a browserAction to pageAction it could be made to appear only on a mastodon website, thus decluttering the extension list in other cases.

**Comment by joshka** [comment]
This is definitely on my todo list as it makes much more sense for this to be a page action. This was my first web extension, so make it work, then make it good was my approach. Watch this space.

**Comment by joshka** [comment]
Fixed in the latest version.
