### ISSUE TITLE
avoid popup dialog?

### ISSUE THREAD

**Issue by wesinator** [joshka/follow-mastodon-user-webextension#2]
Thanks for providing this extension 

So in Firefox 109, there is a popup warning tied to the host/mastodon instance.
![popup](https://user-images.githubusercontent.com/5124946/216832897-795630bd-a785-4517-b3cf-043f8bd07d63.png)

I think https://github.com/joshka/follow-mastodon-user-webextension/blob/bb35987a8e33929ba343d2a7031c2b90f47275ad/src/follow-user.js#L14 should be changed to use [`windows.create()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create) to avoid this.

I tested with the following change to line 14 but wasn't able to get it working:
```js
            browser.windows.create({
              url: followURL,
              type: "popup",
              height: 600,
              width: 600
            });
```

**Comment by joshka** [comment]
I think the latest version will probably fix this issue. Let me know if it doesn't.
